import Head from "next/head";
import { CreateMember } from "../components/createMember";
import Navbar from "../components/navbar";
import { Proposallist } from "../components/proposalList";
import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";
import { Web3ReactProvider } from "@web3-react/core";
import { Web3Provider } from "@ethersproject/providers";
import 'tailwindcss/tailwind.css'


function getLibrary(provider:any, connector:any) {
  return new Web3Provider(provider)
}

const Home = () => {
  
  const { isMember, loading, account } = useData()
  console.log("isMember",isMember)

  if (loading) {
    return (
      <Web3ReactProvider getLibrary={getLibrary}>
         <div className="h-screen w-screen flex justify-center items-center">
        <div className="text-2xl font-bold text-gray-500">Loading ....</div>
      </div>
      </Web3ReactProvider>
     
    )
  }

  if (!account) {
    return (
      <Web3ReactProvider getLibrary={getLibrary}>
         <div className="h-screen w-screen flex justify-center items-center">
        <div className="text-2xl font-bold text-gray-500">
          Please connect Metamask Wallet
        </div>
      </div>
      </Web3ReactProvider>
     
    )
  }
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <div className={styles.container}>
        <Head>
          <title>Funding DAO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar></Navbar>

        {!isMember && <CreateMember />}
        {isMember && <Proposallist/>}
      </div>
    </Web3ReactProvider>
   
  
  )
}

export default Home
